version: 1
disable_existing_loggers: true

formatters:
  default:
    format: "%(asctime)s [%(threadName)s] [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default

  app:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/app.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  api_rest:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/api-rest.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1

  manager_wifi_bands:
    class: logging.handlers.RotatingFileHandler
    formatter: default
    filename: logs/wifi_bands.log
    maxBytes: 52428800 # 50 Megabytes
    backupCount: 1


root:
  level: WARN
  handlers: [app]

loggers:
  server.app:
    level: INFO
    handlers: [console]
    propagate: no

  server.rest_api:
      level: INFO
      handlers: [console]
      propagate: no

  server.application:
    level: INFO
    handlers: [console]
    propagate: no

  server.managers.wifi_bands_manager:
    level: INFO
    handlers: [manager_wifi_bands]
    propagate: no

  server.managers.smart_band_manager:
    level: INFO
    handlers: [console]
    propagate: no

  server.interfaces.wifi_interface:
    level: INFO
    handlers: [manager_wifi_bands]
    propagate: no

