API_TITLE: ORCHESTRATOR API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# Telnet connection configuration
LIVEBOX_IP_ADDRESS: 192.168.1.1 # LIVEBOX
LIVEBOX_TELNET_PORT: 23
LIVEBOX_LOGIN: root
LIVEBOX_PASSWORD: sah
TELNET_TIMOUT_IN_SECS: 5
LIVEBOX_TELNET_COMMANDS: server/config/telnet_commands.yml



# RESOURCES STATUS POLLING CONFIGURATION
WIFI_COUNTERS_POLLING_PERIOD_IN_SECS: 4


# RPI CLOUD SERVER CONFIGURATION
#RPI_CLOUD_IP: cloudwigreen.ddns.net
RPI_CLOUD_IP: 192.168.1.16  #RPI CLOUD CONNECTED IN LOCAL BOX
#RPI_CLOUD_IP: localhost #VM local
RPI_CLOUD_PORTS:
  - 3000
#  - 3001

# 5GHz ON/OFF CONFIG
RTT_PREDICTOR_SCALER: server/managers/smart_band_manager/scaler/scaler.gz
RTT_PREDICTOR_MODEL: server/managers/smart_band_manager/model/XGBRegressor.sav
PREDICTIONS_NB_OF_SAMPLES: 7
NB_OF_RTT_PREDICTIONS_TO_STORE: 10
MAX_LAST_SEEN_IN_SECS: 10
PREDICTED_RTT_TH_5GHZ_ON: 50
MIN_PREDICTED_RTT_IN_MS: 2 #TODO: review threshold
ON_OFF_5GHZ_SERVICE_ACTIVE: yes
#RTT_PREDICTIONS_CLOUD_IP: 192.168.1.16 # RPI CLOUD
RTT_PREDICTIONS_CLOUD_IP: localhost # RPI CLOUD
RTT_PREDICTIONS_CLOUD_PORT: 22000
RTT_PREDICTIONS_CLOUD_PATH: rtt_prediction
RTT_PREDICTIONS_SERVICE_STATUS_PATH: rtt_prediction_service
